apiVersion: v1
data:
  blobs: |-
    [
      {
        "name": "edp-npm",
        "path": "/nexus-data/blobs/edp-npm"
      },
      {
        "name": "edp-maven",
        "path": "/nexus-data/blobs/edp-maven"
      },
      {
        "name": "edp-python",
        "path": "/nexus-data/blobs/edp-python"
      },
      {
        "name": "edp-dotnet",
        "path": "/nexus-data/blobs/edp-dotnet"
      }
    ]
kind: ConfigMap
metadata:
  labels:
    app: nexus
    {{- include "nexus-operator.labels" . | nindent 4 }}
  name: nexus-blobs