{{- if .Values.nexus.deploy -}}
apiVersion: v2.edp.epam.com/v1
kind: Nexus
metadata:
  name: {{.Values.nexus.name}}
spec:
  edpSpec:
    dnsWildcard: {{ .Values.global.dnsWildCard }}
  keycloakSpec:
    enabled: false
    roles:
      - developer
      - administrator
  users:
  {{- range .Values.global.admins }}
    - username: {{ . }}
      roles:
        - nx-admin
  {{- end }}
  {{- if .Values.nexus.basePath }}
  basePath: "{{ .Values.nexus.basePath }}"
  {{- end }}
{{end}}
