---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-edp-epam-com-v1alpha1-nexusrepository
  failurePolicy: Fail
  name: vnexusrepository.kb.io
  rules:
  - apiGroups:
    - edp.epam.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nexusrepositories
  sideEffects: None
