{{- if .Values.oauth2_proxy.enabled -}}
{{- $kkUrl := .Values.global.keycloakUrl | required ".Values.global.keycloakUrl is required." -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: oauth2-proxy
{{- include "nexus-operator.labels" . | nindent 4 }}
  name: oauth2-proxy-config
data:
  oauth2_proxy.cfg: |-
    allowed_groups = ["role:administrator"]
    allowed_roles = ["administrator"]
    cookie_secure = "false"
    client_id = "nexus"
    email_domains = [ "*" ]
    insecure_oidc_allow_unverified_email = "true"
    oidc_issuer_url = "{{ $kkUrl }}/auth/realms/{{ .Values.global.edpName }}-main"
    pass_access_token = "true"
    pass_authorization_header = "true"
    pass_basic_auth = "false"
    provider = "keycloak-oidc"
    redirect_url = "https://{{ include "nexus-operator.nexusBaseUrl" . }}/oauth2/callback"
    skip_jwt_bearer_tokens = "true"
    upstreams = [ "http://nexus:8081" ]
{{ end }}
