{{- if .Values.oauth2_proxy.enabled -}}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: nexus
spec:
  advancedProtocolMappers: true
  clientId: nexus
  defaultClientScopes:
    - groups
    - edp
  directAccess: false
  targetRealm: {{ .Release.Namespace }}-main
  webUrl: https://{{ include "nexus-operator.nexusBaseUrl" . }}
{{- end -}}
