{{- if .Values.oauth2_proxy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
{{- include "nexus-operator.labels" . | nindent 4 }}
  name: oauth2-proxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oauth2-proxy.selectorLabels" . | indent 4 }}
{{- end -}}
