{{- if .Values.oauth2_proxy.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: oauth2-proxy
{{- include "nexus-operator.labels" . | nindent 4 }}
  name: oauth2-proxy
{{- end -}}
