{{- if .Values.oauth2_proxy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus-proxy
{{- include "nexus-operator.labels" . | nindent 4 }}
  name: nexus-proxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nexus-proxy.selectorLabels" . | indent 4 }}
{{- end -}}
