apiVersion: edp.epam.com/v1alpha1
kind: Nexus
metadata:
  name: nexus-sample
spec:
  url: http://10.25.20.67:8091
  secret: nexus-secret


---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
data:
  user: YWRtaW4=
  password: YWRtaW4=
