apiVersion: edp.epam.com/v1alpha1
kind: NexusRole
metadata:
  name: nexusrole-sample
spec:
  id: test-role
  nexusRef:
    name: nexus-sample
    kind: Nexus
  name: test-role
  description: test-role
  privileges:
    - nx-blobstores-all
