apiVersion: edp.epam.com/v1alpha1
kind: NexusUser
metadata:
  name: user-sample
spec:
  id: test-user
  firstName: John1
  lastName: Doe
  email: test@gmail.com
  secret: $user-secret:password
  roles:
    - nx-admin
  nexusRef:
    name: nexus-sample
    kind: Nexus

---
apiVersion: v1
kind: Secret
metadata:
  name: user-secret
data:
  password: dGVzdA==
