apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nexususers.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: NexusUser
    listKind: NexusUserList
    plural: nexususers
    singular: nexususer
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                ownerName:
                  type: string
                  description: 'property indicates which nexus instance should be taken to initialize correct client'
                userId:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                roles:
                  type: array
                  nullable: true
                  items:
                    type: string
                status:
                  type: string
                  description: 'user status, available options: active, disabled'
              required:
                - ownerName
                - email
                - userId
                - firstName
                - lastName
                - roles
                - status
              type: object
            status:
              type: object
              additionalProperties: true
      subresources:
        status: {}