# permissions for end users to edit nexusroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: nexusrole-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nexus-operator
    app.kubernetes.io/part-of: nexus-operator
    app.kubernetes.io/managed-by: kustomize
  name: nexusrole-editor-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - nexusroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - nexusroles/status
  verbs:
  - get
