# permissions for end users to view nexus.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: nexus-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nexus-operator
    app.kubernetes.io/part-of: nexus-operator
    app.kubernetes.io/managed-by: kustomize
  name: nexus-viewer-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - nexus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - nexus/status
  verbs:
  - get
