# permissions for end users to edit nexusblobstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nexusblobstore-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nexus-operator
    app.kubernetes.io/part-of: nexus-operator
    app.kubernetes.io/managed-by: kustomize
  name: nexusblobstore-editor-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - nexusblobstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - nexusblobstores/status
  verbs:
  - get
