# permissions for end users to view cleanuppolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nexuscleanuppolicy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nexus-operator
    app.kubernetes.io/part-of: nexus-operator
    app.kubernetes.io/managed-by: kustomize
  name: nexuscleanuppolicy-viewer-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - cleanuppolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - cleanuppolicies/status
  verbs:
  - get
