---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: placeholder
rules:
- apiGroups:
  - v2.edp.epam.com
  resources:
  - nexususers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v2.edp.epam.com
  resources:
  - nexususers/finalizers
  verbs:
  - update
- apiGroups:
  - v2.edp.epam.com
  resources:
  - nexususers/status
  verbs:
  - get
  - patch
  - update
