apiVersion: v1.edp.epam.com/v1
kind: NexusUser
metadata:
  labels:
    app.kubernetes.io/name: nexususer
    app.kubernetes.io/instance: nexususer-sample
    app.kubernetes.io/part-of: controller-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller-operator
  name: nexususer-sample
spec:
  # TODO(user): Add fields here
