global:
  edpName: ""
  platform: "openshift"
  admins:
    - "stub_user_one@example.com"
  dnsWildCard:
  openshift:
    deploymentType: "deploymentConfigs"

name: nexus-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  name: epamedp/nexus-operator
  # if not defined then .Chart.AppVersion is used
  version:
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

nexus:
  deploy: true
  name: "nexus"
  image: "sonatype/nexus3"
  version: "3.36.0"
  imagePullPolicy: "IfNotPresent"
  basePath: ""
  imagePullSecrets:
  storage:
    class: gp2
    size: 10Gi
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    annotations: {}
    # pathType is only for k8s >= 1.1=
    pathType: Prefix
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  proxyImage: "quay.io/keycloak/keycloak-gatekeeper:10.0.0"

  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 1.5Gi
