global:
  edpName: ""
  platform: "openshift"
  admins:
    - "stub_user_one@example.com"
  dnsWildCard:

name: nexus-operator
image:
  name: epamedp/nexus-operator
  version: v2.5.0

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

nexus:
  deploy: true
  name: "nexus"
  image: "sonatype/nexus3"
  version: "3.29.0"
  basePath: ""
  imagePullSecrets:
  storage:
    class: gp2
    size: 10G

  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 1.5Gi
