global:
  # -- namespace or a project name (in case of OpenShift)
  edpName: ""
  # -- platform type that can be "kubernetes" or "openshift"
  platform: "kubernetes"
  # -- Administrators of your tenant
  admins:
    - "stub_user_one@example.com"
  # -- a cluster DNS wildcard name
  dnsWildCard:
  openshift:
    # -- Which type of kind will be deployed to Openshift (values: deployments/deploymentConfigs)
    deploymentType: "deployments"

# -- component name
name: nexus-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
   # -- EDP nexus-operator Docker image name. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/nexus-operator)
  repository: epamedp/nexus-operator
  # if not defined then .Chart.AppVersion is used
  # -- EDP nexus-operator Docker image tag. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/nexus-operator/tags)
  tag:
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

nexus:
  # -- Flag to enable/disable Nexus deploy
  deploy: true
  # -- Nexus name
  name: "nexus"
  # --  Image for Nexus. The image can be found on [Dockerhub] (https://hub.docker.com/r/sonatype/nexus3)
  image: "sonatype/nexus3"
  # --  Nexus version. The released version can be found on [Dockerhub](https://hub.docker.com/r/sonatype/nexus3/tags)
  version: "3.43.0"
  imagePullPolicy: "IfNotPresent"

  # --  Base path for Nexus URL e.g. "some/path". With no starting '/'. Default: '/'.
  # basePath:

  # --  Secrets to pull from private Docker registry
  imagePullSecrets:
  # -- Custom environment variables to be used by nexus pod
  env:
    # see recommendation https://help.sonatype.com/repomanager3/product-information/system-requirements
    - name: INSTALL4J_ADD_VM_PARAMS
      value: |-
        -Xms2703M -Xmx2703M
        -XX:MaxDirectMemorySize=2703M
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseCGroupMemoryLimitForHeap
        -Djava.util.prefs.userRoot=/nexus-data/javaprefs
  storage:
    # --  Storageclass for Nexus data volume
    # class: gp2
    # -- Nexus data volume capacity
    size: 10Gi
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  resources:
    limits:
      memory: 6Gi
    requests:
      cpu: 100m
      memory: 2Gi
