{{ if eq .Values.global.platform "kubernetes" }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: nexus
  labels:
    app: nexus
    {{- include "nexus-operator.labels" . | nindent 4 }}
  {{- with .Values.nexus.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{if .Values.nexus.basePath}}{{ .Values.global.dnsWildCard }}{{else}}nexus-{{ .Values.global.edpName }}.{{ .Values.global.dnsWildCard }}{{end}}
      http:
        paths:
          - path: {{if .Values.nexus.basePath}}/{{.Values.nexus.basePath}}{{else}}/{{end}}
            backend:
              serviceName: nexus
              servicePort: 3000
{{ end }}
