apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
    {{- include "nexus-operator.labels" . | nindent 4 }}
  name: nexus
spec:
  ports:
    - name: nexus-http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: nexus
  sessionAffinity: None
  type: ClusterIP