apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  labels:
    app: nexus
    {{- include "nexus-operator.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nexus.storage.size }}
  storageClassName: {{ .Values.nexus.storage.class }}
  volumeMode: Filesystem