apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "nexus-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edp-{{ .Values.name }}-role
subjects:
  - kind: ServiceAccount
    name: edp-{{ .Values.name }}
