{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: edp-{{ .Values.name }}-admin
  labels:
    {{- include "nexus-operator.labels" . | nindent 4 }}
roleRef:
  name: admin
subjects:
  - kind: ServiceAccount
    name: edp-{{ .Values.name }}
    namespace: {{ .Release.Namespace }}
userNames:
  - system:serviceaccount:{{ .Release.Namespace }}:edp-{{ .Values.name }}
groupNames: []
{{- end -}}