{{ if eq .Values.global.platform "openshift" }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
allowedFlexVolumes: []
apiVersion: security.openshift.io/v1
defaultAddCapabilities: []
fsGroup:
  ranges:
    - max: 200
      min: 200
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app: nexus
    {{- include "nexus-operator.labels" . | nindent 4 }}
  name: nexus-{{.Values.global.edpName}}
priority: 1
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: MustRunAs
  uid: 200
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{.Values.global.edpName}}:nexus
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
  {{end}}
