apiVersion: v1
kind: Service
metadata:
  name: edp-nexus-operator-webhook-service
  labels:
    {{- include "nexus-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    name: {{ .Values.name }}
