{{if or (eq .Values.global.platform "kubernetes") (eq .Values.global.openshift.deploymentType "deployments")}}
{{if .Values.nexus.deploy}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus
    {{- include "nexus-operator.labels" . | nindent 4 }}
  {{- with .Values.nexus.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: nexus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nexus
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nexus
    spec:
      {{- if .Values.nexus.imagePullSecrets}}
      imagePullSecrets:
        {{- range .Values.nexus.imagePullSecrets }}
        - {{. -}}
        {{- end -}}
      {{end}}
      containers:
        - env:
            - name: NEXUS_CONTEXT
              value: "{{ include "nexus-operator.nexusBasePath" . }}"
            {{- toYaml .Values.nexus.env | nindent 12 }}
          image: "{{.Values.nexus.image}}:{{.Values.nexus.version}}"
          imagePullPolicy: "{{ .Values.nexus.imagePullPolicy }}"
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 8081
            timeoutSeconds: 1
          name: nexus
          ports:
            - containerPort: 8081
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8081
            timeoutSeconds: 1
          resources:
{{ toYaml .Values.nexus.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /nexus-data
              name: data
            - mountPath: /opt/sonatype/nexus/etc/nexus-default.properties
              name: config
              subPath: nexus-default.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 200
        runAsGroup: 200
        runAsNonRoot: true
        runAsUser: 200
      serviceAccount: nexus
      serviceAccountName: nexus
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nexus-data
        - configMap:
            defaultMode: 420
            name: nexus-nexus-default.properties
          name: config
      {{- with .Values.nexus.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nexus.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nexus.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{end}}
{{end}}
